import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Ensure important classes are not purged
    'btn-primary',
    'btn-secondary',
    'header-button-account',
    'header-button-language-inactive',
    'header-button-menu',
    'unified-primary',
    'unified-bg-primary',
    'unified-text-primary',
    // CSS Variables and custom properties
    '--unified-primary',
    '--unified-primary-hover',
    '--unified-bg-primary',
    '--unified-text-primary',
    '--matmax-purple',
    '--matmax-purple-light',
    '--matmax-purple-dark',
    // Custom component classes
    'safe-padding',
    'header-container',
    'mobile-input-group',
    'mobile-step-container',
    'country-dropdown',
    'mobile-country-dropdown',
    // Admin dashboard classes
    'admin-dashboard',
    'admin-header',
    'admin-sidebar',
    'admin-main-content',
    'dashboard-container',
    'dashboard-card',
    'dashboard-button-primary',
    'dashboard-button-outline',
    'dashboard-button-danger',
    'dashboard-button-toggle-active',
    'dashboard-button-toggle-inactive',
    'dashboard-tabs-list',
    'dashboard-tab-trigger',
    'dashboard-language-tabs',
    'dashboard-language-tab',
    'dashboard-language-tab-active',
    'dashboard-language-tab-inactive',
    'dashboard-button-reload',
    'dashboard-button-close',
    'dashboard-button-signout',
    'dashboard-dropdown-content',
    'dashboard-dropdown-item',
    'dashboard-text-primary',
    'dashboard-text-secondary',
    'dashboard-text-muted',
    'dashboard-stats-card',
    'dashboard-stats-label',
    'dashboard-stats-value',
    'dashboard-input',
    'dashboard-select',
    'dashboard-badge',
    'dashboard-badge-info',
    'dashboard-badge-success',
    'dashboard-badge-warning',
    'dashboard-badge-gold',
    'dashboard-badge-error',
    'dashboard-card-title',
    'dashboard-card-description',
    'dashboard-label',
    'dashboard-table',
    'dashboard-table-header',
    'dashboard-table-row',
    'dashboard-loading',
    'dashboard-loading-spinner',
    'dashboard-empty',
    'dashboard-empty-icon',
    'dashboard-filter-grid',
    'dashboard-filter-item',
    'dashboard-filter-label',
    'dashboard-modal',
    'dashboard-modal-title',
    'dashboard-modal-description',
    // Mobile classes
    'mobile-menu',
    'mobile-menu-backdrop',
    'mobile-menu-container',
    'mobile-container',
    'mobile-container-fixed',
    'mobile-content',
    'mobile-touch-feedback',
    'mobile-scroll-smooth',
    'mobile-scrollable',
    'mobile-safe-area',
    'mobile-nav-safe',
    'mobile-content-safe',
    'mobile-small-phone',
    'mobile-medium-phone',
    'mobile-large-phone',
    'mobile-tablet',
    'mobile-spacing',
    'mobile-spacing-lg',
    'mobile-text-scale',
    'mobile-heading-scale',
    'mobile-container-optimized',
    'mobile-slide-in',
    'mobile-fade-in',
    'mobile-bounce',
    'mobile-gesture-feedback',
    // Chat classes
    'chat-window',
    'chat-window-header',
    'chat-window-messages',
    'chat-message-user',
    'chat-message-assistant',
    'chat-input',
    'chat-button-send',
    'chat-toggle-button',
    'chat-typing-indicator',
    'chat-typing-dot',
    'chat-scrollbar',
    'chat-message-enter',
    'chat-window-enter',
    'chat-window-exit',
    // Animation classes
    'cosmic-glow',
    'star-twinkle',
    'star-drift',
    'cosmic-pulse',
    'nebula-flow',
    'orbit-motion',
    'shooting-star',
    'particle-trail',
    'cosmic-glow-small',
    'cosmic-glow-enhanced',
    'shimmer',
    'loading-shimmer',
    'fadeSlideIn',
    'calendar-month-enter',
    'selectionPulse',
    'time-slot-selected',
    'week-slide-in',
    'view-toggle-active',
    'navigationPulse',
    'navigation-button-enhanced',
    'slideInRight',
    'fadeIn',
    'slideOutRight',
    'fadeOut',
    'slideInFromRight',
    'menu-slide-in',
    'menu-slide-out',
    'chatSlideIn',
    'chatSlideOut',
    'chatBounceIn',
    'mobileSlideIn',
    'mobileFadeIn',
    'mobileBounce',
    // Utility classes
    'line-clamp-2',
    'sr-only',
    'card-base',
    'card-hover',
    'bg-light',
    'text-primary',
    'text-muted',
    'gradient-purple',
    'hover-lift',
    'hover-scale',
    'product-grid',
    'schedule-grid',
    'schedule-cell',
    'matpass-card',
    'custom-scrollbar',
    'country-menu-scroll',
    'focus-visible',
    'touch-manipulation',
    'inner-page',
    'packages-page',
    'booking-page',
    'homepage',
    'payment-step',
    'fullpage-container',
    'section-content',
    'nav-dot-active',
    'fixed-element-backdrop',
    // Add any other custom classes that might be purged
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        heading: 'var(--font-heading)',
        body: 'var(--font-body)',
      },
    },
  },
  plugins: [],
}

export default config
