services:
  - type: web
    name: rasa-server
    runtime: docker
    dockerfilePath: ./Dockerfile.rasa
    dockerContext: .
    dockerBuildArgs:
      - BUILDKIT_INLINE_CACHE=1
    envVars:
      - key: PORT
        generateValue: true
      - key: RASA_MODEL_SERVER
        value: null
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
    healthCheckPath: /webhooks/rest/
    plan: starter

  - type: web
    name: rasa-actions
    runtime: docker
    dockerfilePath: ./Dockerfile.rasa
    dockerContext: .
    command: python -m rasa run actions --port $ACTIONS_PORT
    envVars:
      - key: ACTIONS_PORT
        value: 5055
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RASA_MODEL_SERVER
        value: null
    plan: starter
