export interface Country {
  code: string;
  flag: string;
  name: string;
  country: string;
}

export const countries: Country[] = [
  // Most relevant countries first
  { code: '+51', flag: '🇵🇪', name: 'Peru', country: 'PE' },
  { code: '+1', flag: '🇺🇸', name: 'United States', country: 'US' },
  { code: '+1', flag: '🇨🇦', name: 'Canada', country: 'CA' },
  { code: '+52', flag: '🇲🇽', name: 'Mexico', country: 'MX' },
  
  // Latin American countries
  { code: '+54', flag: '🇦🇷', name: 'Argentina', country: 'AR' },
  { code: '+55', flag: '🇧🇷', name: 'Brazil', country: 'BR' },
  { code: '+56', flag: '🇨🇱', name: 'Chile', country: 'CL' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia', country: 'CO' },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela', country: 'VE' },
  { code: '+593', flag: '🇪🇨', name: 'Ecuador', country: 'EC' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia', country: 'BO' },
  { code: '+598', flag: '🇺🇾', name: 'Uruguay', country: 'UY' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay', country: 'PY' },
  { code: '+507', flag: '🇵🇦', name: 'Panama', country: 'PA' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica', country: 'CR' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala', country: 'GT' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras', country: 'HN' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador', country: 'SV' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua', country: 'NI' },
  { code: '+509', flag: '🇭🇹', name: 'Haiti', country: 'HT' },
  { code: '+1809', flag: '🇩🇴', name: 'Dominican Republic', country: 'DO' },
  { code: '+1876', flag: '🇯🇲', name: 'Jamaica', country: 'JM' },
  { code: '+1242', flag: '🇧🇸', name: 'Bahamas', country: 'BS' },
  { code: '+1246', flag: '🇧🇧', name: 'Barbados', country: 'BB' },
  { code: '+1268', flag: '🇦🇬', name: 'Antigua and Barbuda', country: 'AG' },
  { code: '+1767', flag: '🇩🇲', name: 'Dominica', country: 'DM' },
  { code: '+1758', flag: '🇱🇨', name: 'Saint Lucia', country: 'LC' },
  { code: '+1784', flag: '🇻🇨', name: 'Saint Vincent and the Grenadines', country: 'VC' },
  { code: '+1869', flag: '🇰🇳', name: 'Saint Kitts and Nevis', country: 'KN' },
  { code: '+1868', flag: '🇹🇹', name: 'Trinidad and Tobago', country: 'TT' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana', country: 'GY' },
  { code: '+597', flag: '🇸🇷', name: 'Suriname', country: 'SR' },
  { code: '+1264', flag: '🇦🇮', name: 'Anguilla', country: 'AI' },
  { code: '+1473', flag: '🇬🇩', name: 'Grenada', country: 'GD' },
  { code: '+1787', flag: '🇵🇷', name: 'Puerto Rico', country: 'PR' },
  { code: '+1340', flag: '🇻🇮', name: 'U.S. Virgin Islands', country: 'VI' },
  { code: '+1284', flag: '🇻🇬', name: 'British Virgin Islands', country: 'VG' },
  { code: '+1649', flag: '🇹🇨', name: 'Turks and Caicos Islands', country: 'TC' },
  { code: '+1345', flag: '🇰🇾', name: 'Cayman Islands', country: 'KY' },
  { code: '+1441', flag: '🇧🇲', name: 'Bermuda', country: 'BM' },
  { code: '+1664', flag: '🇲🇸', name: 'Montserrat', country: 'MS' },
  { code: '+590', flag: '🇬🇵', name: 'Guadeloupe', country: 'GP' },
  { code: '+596', flag: '🇲🇶', name: 'Martinique', country: 'MQ' },
  { code: '+594', flag: '🇬🇫', name: 'French Guiana', country: 'GF' },
  
  // European countries
  { code: '+34', flag: '🇪🇸', name: 'Spain', country: 'ES' },
  { code: '+33', flag: '🇫🇷', name: 'France', country: 'FR' },
  { code: '+49', flag: '🇩🇪', name: 'Germany', country: 'DE' },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom', country: 'GB' },
  { code: '+39', flag: '🇮🇹', name: 'Italy', country: 'IT' },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands', country: 'NL' },
  { code: '+32', flag: '🇧🇪', name: 'Belgium', country: 'BE' },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland', country: 'CH' },
  { code: '+43', flag: '🇦🇹', name: 'Austria', country: 'AT' },
  { code: '+45', flag: '🇩🇰', name: 'Denmark', country: 'DK' },
  { code: '+46', flag: '🇸🇪', name: 'Sweden', country: 'SE' },
  { code: '+47', flag: '🇳🇴', name: 'Norway', country: 'NO' },
  { code: '+358', flag: '🇫🇮', name: 'Finland', country: 'FI' },
  { code: '+30', flag: '🇬🇷', name: 'Greece', country: 'GR' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', country: 'PT' },
  { code: '+48', flag: '🇵🇱', name: 'Poland', country: 'PL' },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic', country: 'CZ' },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia', country: 'SK' },
  { code: '+36', flag: '🇭🇺', name: 'Hungary', country: 'HU' },
  { code: '+40', flag: '🇷🇴', name: 'Romania', country: 'RO' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria', country: 'BG' },
  { code: '+385', flag: '🇭🇷', name: 'Croatia', country: 'HR' },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia', country: 'SI' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia', country: 'RS' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro', country: 'ME' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia and Herzegovina', country: 'BA' },
  { code: '+389', flag: '🇲🇰', name: 'North Macedonia', country: 'MK' },
  { code: '+355', flag: '🇦🇱', name: 'Albania', country: 'AL' },
  { code: '+383', flag: '🇽🇰', name: 'Kosovo', country: 'XK' },
  { code: '+370', flag: '🇱🇹', name: 'Lithuania', country: 'LT' },
  { code: '+371', flag: '🇱🇻', name: 'Latvia', country: 'LV' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia', country: 'EE' },
  { code: '+7', flag: '🇷🇺', name: 'Russia', country: 'RU' },
  { code: '+375', flag: '🇧🇾', name: 'Belarus', country: 'BY' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine', country: 'UA' },
  { code: '+373', flag: '🇲🇩', name: 'Moldova', country: 'MD' },
  { code: '+354', flag: '🇮🇸', name: 'Iceland', country: 'IS' },
  { code: '+353', flag: '🇮🇪', name: 'Ireland', country: 'IE' },
  { code: '+44', flag: '🇮🇲', name: 'Isle of Man', country: 'IM' },
  { code: '+44', flag: '🇯🇪', name: 'Jersey', country: 'JE' },
  { code: '+44', flag: '🇬🇬', name: 'Guernsey', country: 'GG' },
  { code: '+377', flag: '🇲🇨', name: 'Monaco', country: 'MC' },
  { code: '+378', flag: '🇸🇲', name: 'San Marino', country: 'SM' },
  { code: '+379', flag: '🇻🇦', name: 'Holy See', country: 'VA' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein', country: 'LI' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra', country: 'AD' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg', country: 'LU' },
  { code: '+356', flag: '🇲🇹', name: 'Malta', country: 'MT' },
  { code: '+357', flag: '🇨🇾', name: 'Cyprus', country: 'CY' },
  { code: '+90', flag: '🇹🇷', name: 'Turkey', country: 'TR' },
  
  // Rest of the world
  { code: '+93', flag: '🇦🇫', name: 'Afghanistan', country: 'AF' },
  { code: '+213', flag: '🇩🇿', name: 'Algeria', country: 'DZ' },
  { code: '+1684', flag: '🇦🇸', name: 'American Samoa', country: 'AS' },
  { code: '+244', flag: '🇦🇴', name: 'Angola', country: 'AO' },
  { code: '+672', flag: '🇦🇶', name: 'Antarctica', country: 'AQ' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia', country: 'AM' },
  { code: '+297', flag: '🇦🇼', name: 'Aruba', country: 'AW' },
  { code: '+61', flag: '🇦🇺', name: 'Australia', country: 'AU' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaijan', country: 'AZ' },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain', country: 'BH' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh', country: 'BD' },
  { code: '+229', flag: '🇧🇯', name: 'Benin', country: 'BJ' },
  { code: '+975', flag: '🇧🇹', name: 'Bhutan', country: 'BT' },
  { code: '+246', flag: '🇮🇴', name: 'British Indian Ocean Territory', country: 'IO' },
  { code: '+673', flag: '🇧🇳', name: 'Brunei', country: 'BN' },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', country: 'BF' },
  { code: '+257', flag: '🇧🇮', name: 'Burundi', country: 'BI' },
  { code: '+855', flag: '🇰🇭', name: 'Cambodia', country: 'KH' },
  { code: '+237', flag: '🇨🇲', name: 'Cameroon', country: 'CM' },
  { code: '+238', flag: '🇨🇻', name: 'Cape Verde', country: 'CV' },
  { code: '+236', flag: '🇨🇫', name: 'Central African Republic', country: 'CF' },
  { code: '+235', flag: '🇹🇩', name: 'Chad', country: 'TD' },
  { code: '+86', flag: '🇨🇳', name: 'China', country: 'CN' },
  { code: '+61', flag: '🇨🇽', name: 'Christmas Island', country: 'CX' },
  { code: '+61', flag: '🇨🇨', name: 'Cocos Islands', country: 'CC' },
  { code: '+269', flag: '🇰🇲', name: 'Comoros', country: 'KM' },
  { code: '+242', flag: '🇨🇬', name: 'Congo', country: 'CG' },
  { code: '+243', flag: '🇨🇩', name: 'Congo, Democratic Republic', country: 'CD' },
  { code: '+682', flag: '🇨🇰', name: 'Cook Islands', country: 'CK' },
  { code: '+225', flag: '🇨🇮', name: 'Côte d\'Ivoire', country: 'CI' },
  { code: '+53', flag: '🇨🇺', name: 'Cuba', country: 'CU' },
  { code: '+253', flag: '🇩🇯', name: 'Djibouti', country: 'DJ' },
  { code: '+20', flag: '🇪🇬', name: 'Egypt', country: 'EG' },
  { code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea', country: 'GQ' },
  { code: '+291', flag: '🇪🇷', name: 'Eritrea', country: 'ER' },
  { code: '+251', flag: '🇪🇹', name: 'Ethiopia', country: 'ET' },
  { code: '+500', flag: '🇫🇰', name: 'Falkland Islands', country: 'FK' },
  { code: '+298', flag: '🇫🇴', name: 'Faroe Islands', country: 'FO' },
  { code: '+679', flag: '🇫🇯', name: 'Fiji', country: 'FJ' },
  { code: '+241', flag: '🇬🇦', name: 'Gabon', country: 'GA' },
  { code: '+220', flag: '🇬🇲', name: 'Gambia', country: 'GM' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia', country: 'GE' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana', country: 'GH' },
  { code: '+350', flag: '🇬🇮', name: 'Gibraltar', country: 'GI' },
  { code: '+299', flag: '🇬🇱', name: 'Greenland', country: 'GL' },
  { code: '+224', flag: '🇬🇳', name: 'Guinea', country: 'GN' },
  { code: '+245', flag: '🇬🇼', name: 'Guinea-Bissau', country: 'GW' },
  { code: '+852', flag: '🇭🇰', name: 'Hong Kong', country: 'HK' },
  { code: '+91', flag: '🇮🇳', name: 'India', country: 'IN' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', country: 'ID' },
  { code: '+98', flag: '🇮🇷', name: 'Iran', country: 'IR' },
  { code: '+964', flag: '🇮🇶', name: 'Iraq', country: 'IQ' },
  { code: '+972', flag: '🇮🇱', name: 'Israel', country: 'IL' },
  { code: '+81', flag: '🇯🇵', name: 'Japan', country: 'JP' },
  { code: '+962', flag: '🇯🇴', name: 'Jordan', country: 'JO' },
  { code: '+7', flag: '🇰🇿', name: 'Kazakhstan', country: 'KZ' },
  { code: '+254', flag: '🇰🇪', name: 'Kenya', country: 'KE' },
  { code: '+686', flag: '🇰🇮', name: 'Kiribati', country: 'KI' },
  { code: '+850', flag: '🇰🇵', name: 'North Korea', country: 'KP' },
  { code: '+82', flag: '🇰🇷', name: 'South Korea', country: 'KR' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', country: 'KW' },
  { code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan', country: 'KG' },
  { code: '+856', flag: '🇱🇦', name: 'Laos', country: 'LA' },
  { code: '+961', flag: '🇱🇧', name: 'Lebanon', country: 'LB' },
  { code: '+266', flag: '🇱🇸', name: 'Lesotho', country: 'LS' },
  { code: '+231', flag: '🇱🇷', name: 'Liberia', country: 'LR' },
  { code: '+218', flag: '🇱🇾', name: 'Libya', country: 'LY' },
  { code: '+853', flag: '🇲🇴', name: 'Macao', country: 'MO' },
  { code: '+261', flag: '🇲🇬', name: 'Madagascar', country: 'MG' },
  { code: '+265', flag: '🇲🇼', name: 'Malawi', country: 'MW' },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia', country: 'MY' },
  { code: '+960', flag: '🇲🇻', name: 'Maldives', country: 'MV' },
  { code: '+223', flag: '🇲🇱', name: 'Mali', country: 'ML' },
  { code: '+692', flag: '🇲🇭', name: 'Marshall Islands', country: 'MH' },
  { code: '+222', flag: '🇲🇷', name: 'Mauritania', country: 'MR' },
  { code: '+230', flag: '🇲🇺', name: 'Mauritius', country: 'MU' },
  { code: '+262', flag: '🇾🇹', name: 'Mayotte', country: 'YT' },
  { code: '+691', flag: '🇫🇲', name: 'Micronesia', country: 'FM' },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar', country: 'MM' },
  { code: '+264', flag: '🇳🇦', name: 'Namibia', country: 'NA' },
  { code: '+674', flag: '🇳🇷', name: 'Nauru', country: 'NR' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', country: 'NP' },
  { code: '+687', flag: '🇳🇨', name: 'New Caledonia', country: 'NC' },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand', country: 'NZ' },
  { code: '+227', flag: '🇳🇪', name: 'Niger', country: 'NE' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', country: 'NG' },
  { code: '+683', flag: '🇳🇺', name: 'Niue', country: 'NU' },
  { code: '+672', flag: '🇳🇫', name: 'Norfolk Island', country: 'NF' },
  { code: '+1670', flag: '🇲🇵', name: 'Northern Mariana Islands', country: 'MP' },
  { code: '+968', flag: '🇴🇲', name: 'Oman', country: 'OM' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan', country: 'PK' },
  { code: '+680', flag: '🇵🇼', name: 'Palau', country: 'PW' },
  { code: '+970', flag: '🇵🇸', name: 'Palestine', country: 'PS' },
  { code: '+675', flag: '🇵🇬', name: 'Papua New Guinea', country: 'PG' },
  { code: '+63', flag: '🇵🇭', name: 'Philippines', country: 'PH' },
  { code: '+64', flag: '🇵🇳', name: 'Pitcairn', country: 'PN' },
  { code: '+974', flag: '🇶🇦', name: 'Qatar', country: 'QA' },
  { code: '+262', flag: '🇷🇪', name: 'Réunion', country: 'RE' },
  { code: '+250', flag: '🇷🇼', name: 'Rwanda', country: 'RW' },
  { code: '+290', flag: '🇸🇭', name: 'Saint Helena', country: 'SH' },
  { code: '+685', flag: '🇼🇸', name: 'Samoa', country: 'WS' },
  { code: '+239', flag: '🇸🇹', name: 'São Tomé and Príncipe', country: 'ST' },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia', country: 'SA' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal', country: 'SN' },
  { code: '+248', flag: '🇸🇨', name: 'Seychelles', country: 'SC' },
  { code: '+232', flag: '🇸🇱', name: 'Sierra Leone', country: 'SL' },
  { code: '+65', flag: '🇸🇬', name: 'Singapore', country: 'SG' },
  { code: '+677', flag: '🇸🇧', name: 'Solomon Islands', country: 'SB' },
  { code: '+252', flag: '🇸🇴', name: 'Somalia', country: 'SO' },
  { code: '+27', flag: '🇿🇦', name: 'South Africa', country: 'ZA' },
  { code: '+500', flag: '🇬🇸', name: 'South Georgia and the South Sandwich Islands', country: 'GS' },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', country: 'LK' },
  { code: '+249', flag: '🇸🇩', name: 'Sudan', country: 'SD' },
  { code: '+47', flag: '🇸🇯', name: 'Svalbard and Jan Mayen', country: 'SJ' },
  { code: '+268', flag: '🇸🇿', name: 'Swaziland', country: 'SZ' },
  { code: '+963', flag: '🇸🇾', name: 'Syria', country: 'SY' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwan', country: 'TW' },
  { code: '+992', flag: '🇹🇯', name: 'Tajikistan', country: 'TJ' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania', country: 'TZ' },
  { code: '+66', flag: '🇹🇭', name: 'Thailand', country: 'TH' },
  { code: '+670', flag: '🇹🇱', name: 'Timor-Leste', country: 'TL' },
  { code: '+228', flag: '🇹🇬', name: 'Togo', country: 'TG' },
  { code: '+690', flag: '🇹🇰', name: 'Tokelau', country: 'TK' },
  { code: '+676', flag: '🇹🇴', name: 'Tonga', country: 'TO' },
  { code: '+216', flag: '🇹🇳', name: 'Tunisia', country: 'TN' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistan', country: 'TM' },
  { code: '+688', flag: '🇹🇻', name: 'Tuvalu', country: 'TV' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda', country: 'UG' },
  { code: '+971', flag: '🇦🇪', name: 'United Arab Emirates', country: 'AE' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistan', country: 'UZ' },
  { code: '+678', flag: '🇻🇺', name: 'Vanuatu', country: 'VU' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', country: 'VN' },
  { code: '+681', flag: '🇼🇫', name: 'Wallis and Futuna', country: 'WF' },
  { code: '+212', flag: '🇪🇭', name: 'Western Sahara', country: 'EH' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen', country: 'YE' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia', country: 'ZM' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabwe', country: 'ZW' }
];