-- Simple RLS disable for testing
ALTER TABLE currencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_durations DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_prices DISABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
